/*
 * The authorization paragraph from "KIBA Lending Application v6.pdf",
 * VERBATIM. It's shown on the review screen so the applicant reads what
 * they're agreeing to before SignWell; the signature in SignWell, on the PDF
 * itself, is what binds.
 *
 * The typos ("TransUnion,Experian", "requesting,receiving", "thisApplication")
 * are in the source and are kept. Like the legal pages, this text is fixed:
 * a correction comes from the business as a new version of the PDF, and then
 * this is replaced to match it.
 */
export const AUTHORIZATION_TEXT =
  'By signing below, each of the above-listed business and business owners/officers/members (individually and collectively, the “Applicant”) certifies that Applicant is authorized to submit this Application on behalf of the above-named business. Applicant certifies that all information and documents submitted in connection with this Application are true, correct and complete and may be relied upon by Kingdom Impact Business Advisors. Applicant authorizes MBS Holdings LLC dba Kingdom Impact Business Advisors to share this Application and all supporting documentation with each of its representatives, successors, assignees, affiliates, and designees, including third-party lenders (collectively “Assignees”) that may be involved with the acquiring of commercial loans and/or other products. Applicant further authorizes Kingdom Impact Business Advisors and all Assignees to request, receive, and review any investigative or credit reports, including comprehensive business and personal credit histories or hard credit pulls, and any other information regarding the Applicant and its owners and/or principals from third parties deemed necessary by Kingdom Impact Business Advisors or Assignees to verify any information provided on the Application including without limitation credit card processor statements and bank statements, from one or more consumer reporting agencies, such as TransUnion,Experian, and Equifax, and from other credit bureaus, banks, creditors and other third parties. Applicant also consents to the release, by any credit or financial institution, of any information relating to Applicant, to Kingdom Impact Business Advisors and to each of the Assignees on its own behalf. Applicant also consents to email and/or text/SMS/fax messages at the phone number(s) provided above, including your wireless number, using an automated telephone dialing system or other similar system for marketing purposes by Kingdom Impact Business Advisors and/or third-party lenders, as well as their respective affiliates or agents acting on their behalf. Furthermore, Applicant hereby waives and releases any claims against Kingdom Impact Business Advisors, all Assignees, and any information-providers arising from any act or omission relating to the requesting,receiving, or release of the information obtained in connection with thisApplication.';
